apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mongo
  namespace: dev
spec:
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      name: mongo
      labels:
        app: mongo
    spec:
      volumes:
        - name: hostpathvol
          hostPath:
            path: /tmp/mongodb/
      containers:
        - name: mongo
          image: mongo
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: devdb
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: devdb123
          volumeMounts:
            - name: hostpathvol
              mountPath: /data/db

---
# Service for mongo 
apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: dev
spec:
  selector:
    app: mongo
  ports:
     - port: 27017
       targetPort: 27017
  type: ClusterIP
