apiVersion: apps/v1
kind: Deployment
metadata:
  name: springapp
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springapp
  template:
    metadata:
      name: springapp
      labels:
        app: springapp
    spec:
      containers:
        - name: springapp
          image: acadalearning/spring-boot-mongo:latest
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_DB_USERNAME
              value: devdb
            - name: MONGO_DB_PASSWORD
              value: devdb123
            - name: MONGO_DB_HOSTNAME
              value: mongo
---
# Service for the springapp

apiVersion: v1
kind: Service
metadata:
  name: springapp
  namespace: dev
spec:
  selector:
    app: springapp
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30700
  type: NodePort
